spring:
  data:
    rest:
      base-path: /api/entities
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

tm:
  max-sessions: 100
  debug-enabled: true
  debug-participant-enabled: true

management:
  contextPath: /admin

